allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  onnxruntime-node: true
  prisma: true
  protobufjs: true
  workerd: true
